### ISSUE TITLE
doesnt work with nuxt

### ISSUE THREAD

**Issue by khairulhaaziq** [selemondev/vue-animated-counter#4]
hi interesting project! as most of the current available are old and unmaintained, yours seems actively maintained and good docs, however I tried it with my nuxt project and doesnt seem to work. even tried wrapping with clientonly and fixed values. Can you let me know how to get it to work or once it is working?

**Comment by selemondev** [comment]
Hello @khairulhaaziq , thank you for trying out my project and I will get back to you as soon as possible.

**Comment by philipimperato** [comment]
![image](https://github.com/selemondev/vue-animated-counter/assets/2430560/70311f2d-9f68-4117-a4cd-3c9597d4fd92)

It appears that here is a type issue when using the docs with Nuxt 3?

**Comment by selemondev** [comment]
> ![image](https://private-user-images.githubusercontent.com/2430560/290009577-70311f2d-9f68-4117-a4cd-3c9597d4fd92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MzU5NDYsIm5iZiI6MTcwMjUzNTY0NiwicGF0aCI6Ii8yNDMwNTYwLzI5MDAwOTU3Ny03MDMxMWYyZC05ZjY4LTQxMTctYTRjZC0zYzk1OTdkNGZkOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDYzNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M3OGIzOGJmNjBlYzc2ZDBlNDRkOWU1NGI2NzY3MTBjMzczMWEyOWY4YjVhZjZiMjM2MDdkZTM5ZmFkODA5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IMVX9xDEVxYE51BzlQklTrIv0mBXcuLidBvMOm8A6DU)
> 
> It appears that here is a type issue when using the docs with Nuxt 3?

Hey @philipimperato, the docs have been updated accordingly. Replace `nuxtApp.vueApp.use(AnimatedCounter)` with `nuxtApp.vueApp.component('AnimatedCounter', AnimatedCounter)`, and this adjustment should resolve the type issue. 😄
